//Developed by A. Reynaud
//10/23/2017
//Ver 0.1.10
let p0 = ["If she could count the stars and the patterns they make up, she'd be more than happy to spend her night beneath the ceiling of this laboratory. Unfortunately, the clever engineers of the Majorana Research Facility didn’t think to paint the ceiling with a fake starry night. If she can't count the stars, she may as well not even go to sleep.", "If she could count the stars and all the constellations they make up, she'd be more than happy to spend her night beneath the ceiling of this laboratory. Unfortunately, the brilliant engineers of the Majorana Research Facility didn’t think to paint the ceiling with constellations. If she can't count the stars, she may as well not even go to sleep.", "If she could count the stars and all the constellations they call home, she'd be delighted to spend her night beneath the ceiling of this laboratory. Unfortunately, the brilliant engineers of the Majorana Research Facility didn’t think to decorate the ceiling with constellations. If she can't count the stars, albeit artificial stars, she may as well not even go to sleep."];
let p1 = ["Would it be too much to ask Dr. Norton to gas the room and help her and Alan go to sleep faster? Perhaps it'd be a bit too much for Alan, being that he hasn't even moved in his spot for at least an hour at this point. At least in his case, he's all too used to having to change to his surroundings; knowing the fact that the first thing she ever saw him do was run away from the Los Abismos security officers, Jocelyn can't begin to picture the kind of things he must be used to if he's sleeping so soundly now. Perhaps he's run into an enemy military at some point in his life?", "Would it be too much to ask Dr. Norton to gas the room and help her and Alan go to sleep quicker? Perhaps it'd be a bit too much for Alan, considering he hasn't even shifted in his spot for at least an hour at this point. At least in his case, he's all too used to having to adapt to his surroundings; considering the fact that the first thing she ever saw him do was run away from the Los Abismos security officers, Jocelyn can't begin to imagine the kind of things he must be used to if he's sleeping so soundly now. Perhaps he's run into an enemy military at some point in his life?", "Would it be too much to ask Dr. Norton to gas the room and make the stages of sleep come that much quicker? Perhaps it'd be a bit too much for Alan, considering he hasn't even shifted in his spot for at least an hour at this point. At least in his case, he's all too used to having to adapt to his milieu; considering the fact that the first thing she ever saw him do was run away from the Los Abismos security officers, Jocelyn can't begin to imagine the horrors he must be used to if he's sleeping so soundly now. Perhaps he's run into an enemy militia at some point in his life?"];
let p2 = ["Better question: <i>The military's gone, right?</i> The thought forces her to suddenly open her eyes. <i>Oh, please tell me they haven't followed us down here.</i>", "Better question: <i>The military's gone, right?</i> The thought forces her eyes wide open in the blackness. <i>Oh, please tell me they haven't followed us down here.</i>", "Better question: <i>The military's gone, right?</i> The thought forces her eyes wide open in the blackness. <i>Oh, please tell me they haven't stalked us.</i>"];
let p3 = ["Almost just after those thoughts cross her mind, she flinches. <i>What was that?!</i> she silently screams. Any urge to sleep is immediately shaken out of her as the sounds of baby steps start ringing in her ears; they're so quiet that she can't tell if there is actually someone else nearby or if her mind is just playing tricks on her.", "Almost immediately after those thoughts cross her mind, she flinches. <i>What was that?!</i> she silently shrieks. Any urge to sleep is immediately shaken out of her as the sounds of baby steps start ringing in her ears; they're so quiet that she can't tell if there is actually someone else nearby or if her mind is just playing tricks on her.", "Almost immediately after those thoughts cross her mind, she flinches. <i>What was that?!</i> she silently shrieks. Any ounce of melatonin is abruptly shaken from her as the sounds of baby steps murmur in her ears; they're so soft that she can't tell if there is actually someone else nearby or if her mind is just playing a foul prank on her."];
let p4 = ["She hears something else and struggles to keep herself under control. Thirteen years old, she has a habit of squealing when something seems to be going wrong—especially when the thing going wrong happens to be something she's not too familiar with. It doesn't help that she's not the kind of person who knows much about how to handle the military when it's up on your butt.", "She hears something else and struggles to keep herself under control. Thirteen years old, she has a tendency to squeal when something seems to be going awry—especially when the thing going wrong happens to be something she's not too familiar with. It doesn't help that she's not the kind of person who knows much about how to handle the military when it's coming up on your tail.", "She hears more noise and struggles to keep her composure. Thirteen years old, she has a tendency to squeal when something seems to be going awry—especially when the thing going wrong happens to be conundrum she's not too familiar with. It doesn't help that she's not the kind of person to have any knowledge of on how to handle the military when it's coming up on your tail."];
let p5 = ["Right now she can recall what her brother would tell her about these kinds of situations—that as long as she ignored them, everything would be fine. He'd tell her that it always worked for him; it's too bad he was lying. Even if she stayed still now and ignored the problem, Jocelyn would still get caught; the noise and all the tension it's bringing has caused her to start trembling in her spot. It doesn't help that she can't just hide under a blanket, pillow, or mattress, since Norton wasn't even able to provide beds in this place. Instead the two of them are just tripping hazards in the event that a sneaky soldier manages to completely miss seeing the two of them on the floor.", "Right now she can recall what her brother would tell her about these kinds of situations—that as long as she ignored them, everything would be fine. He'd tell her that it has always worked for him; it's too bad he was bluffing. Even if she remained still now and ignored the problem, Jocelyn would still get caught; the noise and all the tension it's bringing has caused her to start trembling in her spot. It doesn't help that she can't just hide under a blanket, pillow, or mattress, since Norton wasn't even able to provide beds in this place. Instead Jocelyn and Alan are just tripping hazards in the event that a stealthy soldier manages to completely miss seeing the two of them on lying the floor.", "Right now she can recall what her brother would tell her about these kinds of scenarios—that as long as she ignored them, everything would be fine. He'd tell her that it has always worked for him; it's too bad he was bluffing. Even if she remained still now and ignorant, Jocelyn would certainly be captured; the noise and all the tension it's bringing has caused her to start trembling on the spot. It doesn't help that she can't just hide under a blanket, cushion, or mattress, since Norton wasn't even able to provide beds in this lab room. Instead Jocelyn and Alan are just tripping hazards in the event that a stealthy soldier completely neglects seeing either of them on lying the floor."];
let p6 = ["She looks over at Alan and sees he's somehow still sound asleep. He's not picking up this noise at all.", "She glances over at Alan and sees he's somehow still sound asleep. He can't detect any noise at all.", "She glances over at Alan and finds he's somehow still trapped in deep sleep, unable to detect any noise at all."];
let p7 = ["<i>Maybe I'm just hearing things after all?</i>", "<i>Maybe I'm just imagining things after all?</i>", "<i>Maybe it's just my imagination after all?</i>"];
let p8 = ["She can't be too sure. Part of her wants to put her glasses back on, pick up the flashlight, and just look through the room for a moment. It'll be like having a nightlight.", "She can't be too sure. Part of her wants to put her glasses back on, pick up the flashlight, and just scan the room for a moment. It'll be like having a nightlight.", "She can't be certain. A nagging part of her wants to put her glasses back on, pick up the flashlight, and just scan the room for a moment. It'll be like she and Alan have a nightlight."];
let p9 = ["That in mind, Jocelyn pats the floor for her things and proceeds to turn the light on, careful not to break her glasses—though the fact that they've not broken already astounds her. She pushes her thick frames up her nose and looks around to see if anyone else is here. It should just be her and Alan—and possibly Dr. Norton, but she could swear he said he wasn't going to come into the room with them.", "That in mind, Jocelyn pats the floor for her things and proceeds to turn the light on, careful not to break her glasses—though the fact that they haven't shattered already astounds her. She pushes her thick frames up the bridge of her nose and looks around to see if anyone else is here. It should just be her and Alan—and possibly Dr. Norton, but she could swear he said he wasn't going to come into the room with them.", "That in mind, Jocelyn blindly pats the floor for her things and proceeds to turn the light on, careful not to break her glasses—though the fact that they haven't shattered already astounds her. She pushes her thick frames up the bridge of her nose and investigates to see if anyone else is here. It should just be her and Alan—and possibly Dr. Norton, but she is certain that he said he wasn't going to enter the room at any point tonight."];
let p10 = ["Noise again—though this time it's obviously responding to the light: the shaking, unfocused light. <i>Where the hell are they?!</i> Her free hand clasps over her mouth to keep her quiet—but does it really matter how quiet she is now? If there really is someone or something down here, they should have no trouble seeing her now.", "Noise again—though this time it's obviously reacting to the light: the jittering, unfocused light. <i>Where the hell are they?!</i> Her free hand clasps over her mouth to keep her quiet—but does it really matter whether or not she's hushed at this point? If there really is someone or something down here, they should have no trouble spotting her now.", "Noise again—though this time it's obviously reacting to the light: the jittering, unfocused flashlight rays. <i>Where the hell are they?!</i> Her free hand clasps over her mouth to keep her quiet—but now, what does it matter if she's hushed? If there really is someone or something down here, they should have no issues spotting her now."];
let p11 = ["She's sweating more and more by the second—and by the second, it becomes harder for her to keep a tight hold on the flashlight. She's certain by now that these sounds she's hearing aren't coming from her imagination; something else is here and it's going to be the death of her if she doesn't kill it first.", "She's accumulating sweat by the second—and every second makes it all the more difficult for her to keep a firm hold on the flashlight. She's certain by now that these sounds she's hearing aren't mere figments of her imagination; something else is here and it's going to be the death of her if she doesn't kill it first.", "She's accumulating sweat by the second—and every second makes it all the more difficult for her to keep a firm hold on the flashlight. She's certain by now that these sounds she's hearing aren't mere figments of her imagination; something else is lurking about and it's going to be the death of her if she doesn't eliminate it first."];
let p12 = ["It comes to her in a white, fluffy body.", "It approaches her in a white, fluffy figure.", "The culprit approaches her in a white, fluffy figure."];
let p13 = ["&quot;<i>Yah!!</i>&quot; Without hesitation, she slams her flash light down on the intruder, her light almost immediately going out when it hits the floor. The cap goes flying right off the flashlight's head and ends up knocking one of the laboratory's nearby vials off the table, making it shatter, breaking Alan out of his sleep—as if her scream alone weren't already enough to do that.", "&quot;<i>Yah!!</i>&quot; Without hesitation, she pummels her flashlight down on the intruder, her light almost immediately going out when it smacks the floor. The cap goes flinging right off the flashlight's head and ends up knocking one of the laboratory's nearby vials off the table, making it shatter, yanking Alan out of his sleep—as if her scream alone weren't already enough to do that.", "&quot;<i>Yah!!</i>&quot; Without hesitation, she pummels her flashlight down on the intruder, extinguishing her light almost immediately when it smacks the floor. The cap goes flinging right off the flashlight's head and ends up bumping one of the laboratory's nearby vials off the table, making it shatter along the floor, yanking Alan out of his sleep—as if her scream alone weren't already enough to do that."];
let p14 = ["&quot;What was that?&quot; he asks with a yawn. &quot;Is it time to go?&quot;", "&quot;What was that?&quot; he asks, his words covered by a yawn. &quot;Is it time to go?&quot;", "&quot;What was that?&quot; he asks, his words stifled by a yawn. &quot;Is it time to go?&quot;"];
let p15 = ["Before Jocelyn can answer, the laboratory's door opens; it's Dr. Norton. &quot;Are you kids okay?&quot; he blurts, a magnum in his hand. At the same time, he flips the light on and reveals what has happened. It's then when Jocelyn realizes how close her feet are to the shattered glass; had she stood up from where now lies, a few steps forward would have led to serious bleeding.", "Before Jocelyn can answer, the laboratory's door opens; it's Dr. Norton. &quot;Are you kids okay?&quot; he blurts, a magnum in his hand. At the same time, he switches the light on and reveals what has happened. It's then when Jocelyn realizes how close her feet are to the shattered vial; had she stood up from where now lies, a few steps forward would have led to serious bleeding.", "Before Jocelyn can answer, the laboratory's door opens; it's Dr. Norton. &quot;Are you kids okay?&quot; he blurts, a magnum in his hand. At the same time, he switches the light on and reveals what has happened. It's then when Jocelyn discovres how close her feet are to the shattered vial; had she stood up from where now lies, a few steps forward would have led to serious foot trauma."];
let p16 = ["It takes Jocelyn a moment to respond, being that her hearing is slightly muffled by her beating heart. After a moment, she takes a deep breath and sighs, &quot;Yeah—yeah, we're okay. Right, Alan?&quot;", "It takes Jocelyn a moment to respond, considering her hearing is slightly impaired by her thumping heart. After a moment, she takes a deep breath and sighs, &quot;Yeah—yeah, we're okay. Right, Alan?&quot;", "It takes Jocelyn a moment to respond, considering her hearing is slightly impaired by her thumping heart. After a moment, she takes a deep, shaky breath and sighs, &quot;Yeah—yeah, we're okay. Right, Alan?&quot;"];
let p17 = ["Just as she's about to turn her head to the tween boy, she realizes just what it was she'd hit with her flashlight: a white lab mouse. Seeing its dead, messed-up body and blood-red eyes nearly popping from their sockets is enough to make her want to throw up right then and there—as if a dead rat body is the worst thing she's seen this week.", "Just as she's about to turn her head to the teenage boy, she realizes just what it was she'd hit with her flashlight: a white lab mouse. Seeing its dead, mangled body and blood-red eyes nearly bulging out from their sockets is enough to make her want to throw up right then and there—as if a dead rat body is the worst thing she's seen this week.", "Just as she's about to turn her head to the teenage boy, she realizes just what it was she'd killed with her flashlight: a white lab mouse. Seeing its dead, mangled body and blood-red eyes nearly bulging out from their sockets is enough to make her want to vomit right then and there—as if a dead rat body is the most horrendous thing she's seen this week."];
let p18 = ["<i>Are these the kind of animals we'll have to deal with around here?</i> she thinks to herself. <i>I can't tell if I'd rather deal with these or just get myself shot up by the military.</i> It seems like everyone else is okay with these little animals running around, pretending to be a deadly threat when they most likely aren't even rabid. What she had once thought to be an empty lab—a safe spot from the military—is now known to her as a haven for little animals. And everyone is okay with this?", "<i>Are these the kind of animals we'll have to deal with around here?</i> she thinks to herself. <i>I can't tell if I'd rather deal with these or just get myself shot up by the military.</i> It seems like everyone else is okay with these little animals scurrying around, pretending to be a lethal threat when they most likely aren't even rabid. What she had once thought to be an empty lab—a safe spot from the military—is now known to her as a haven for little animals. And everyone is okay with this?", "<i>Are these the kind of animals we'll have to deal with around here?</i> she thinks to herself. <i>I can't tell if I'd rather deal with these or just get myself shot up by the military.</i> It seems like everyone else is okay with these little animals scurrying around, impersonating a lethal threat when they most likely aren't even rabid. What she had once thought to be an empty lab—a safe haven from the military—is now known to her as a haven for pint-sized animals. And everyone is okay with this?"];
let p19 = ["&quot;Yes, I'm okay,&quot; Alan says.", "&quot;Yes, I'm okay,&quot; Alan says.", "&quot;Yes, I'm okay,&quot; Alan says."];
let pages = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19];
//All of these arrays will be replaced by a database file

document.getElementById("fstBtn").onclick = pgFst;
document.getElementById("lstBtn").onclick = pgEnd;
document.getElementById("prvBtn").onclick = pgPrev;
document.getElementById("nxtBtn").onclick = pgNext;
let dLvl = 1; //I may end up starting by having the user select their "reading level" and storing it in dLvl
var pgCount = 0;
var timeTrig = new Boolean(false);
function loadPara() { //load the paragraphs
    document.getElementById("body").innerHTML = pages[pgCount][dLvl]
};
var dicTime = setInterval(function cngDic(){
	if ((dLvl === 0 && timeTrig === true) || (dLvl === 2 && timeTrig === false)) {
	    //this part of the code ensures the dLvl does not go beyond the system's boundaries
	    //going beyond the system boundaries results in "undefined" showing up in the paragraph
	    return dLvl = dLvl;
	} else {
        dLvl--;
        timeTrig = true;
	    alert("Diction level has changed");
	}
}, 30000); //dicTime goes off every 30 seconds (30,000 milliseconds)
window.onload = function() {
    pgCount = 0;
    document.getElementById("prvBtn").disabled = true;
    loadPara();
    dicTime.start();
};

function pgFst() {
    pgCount = 0;
    if (document.getElementById("nxtBtn").disabled === true) {
        document.getElementById("nxtBtn").disabled = false;
    }
    if (document.getElementById("lstBtn").disabled === true) {
        document.getElementById("lstBtn").disabled = false;
    }
    document.getElementById("prvBtn").disabled = true;
    loadPara();
};

function pgEnd() {
    pgCount = 19;
    if (document.getElementById("prvBtn").disabled === true) {
        document.getElementById("prvBtn").disabled = false;
    }
    document.getElementById("nxtBtn").disabled = true;
    loadPara();
};

function pgNext() {
    pgCount++
    if (document.getElementById("prvBtn").disabled === true) {
        document.getElementById("prvBtn").disabled = false;
    }
    if (pgCount === 19) {
        document.getElementById("nxtBtn").disabled = true;
    };
    if (timeTrig === false) {
        dLvl++
    };
    /*if the setInterval has not gone off, dLvl++ IF it's not at 3 already
    * I will need to set up a boolean to count if cngDic has gone off
    * If boolItvl is false, add 1 to dLvl
    * I also need to make it so that clicking any other button shuts the process off
    */
    loadPara();
};

function pgPrev() {
    pgCount--
    if (document.getElementById("nxtBtn").disabled === true) {
        document.getElementById("nxtBtn").disabled = false;
    }
    if (pgCount === 0) {
        document.getElementById("prvBtn").disabled = true;
    };
    loadPara();
};